name: first workflow
env:
  WORKFLOW_VAR: "This variable is declared at the workflow level"

on: 
  workflow_dispatch: 
jobs:
  firstjob: 
    runs-on: ubuntu-latest
    steps:
    - name: firstJob script 
      shell: bash
      run: echo Hello Word! This is first job
    - name: checkout repository
      uses: actions/checkout@v3
    - name: greet a user with the hello world function
      id: greetings
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: 'Ola'
    - name: the greeting time
      run: | 
        echo "The time of greeting at: ${{steps.greetings.outputs.time}}" 
  secondjob: 
    runs-on: ubuntu-latest
    needs: firstjob
    env:   
      JOB_VAR: " This is a job variable" 
    steps:
      - name: secondJob script
        shell: bash
        run: | 
          echo this issecond job
          echo and this is a multi-line script 
      - name: enviroment variable
        env:
          STEP_VAR: "This variable is defined at the step level"
